// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovfxrixldxvgxxojaohi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92ZnhyaXhsZHh2Z3h4b2phb2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzMyMzgsImV4cCI6MjA2MjgwOTIzOH0.1Zo-SOB_hXgMLiYOlnOzEc7nK5KOS5DLIF4-Zct3d0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);